name: GitHub Actions Minutes Datadog Custom Metric

author: Domenic Gosein

description: GitHub Action to send GitHub Actions Minutes Usage to Custom Metric on Datadog.

branding:
  icon: 'clock'  
  color: 'orange'

inputs:
  api_key:
    description: 'Your Datadog API Key from GitHub Actions Secrets'
    required: true
  app_key:
    description: 'Your Datadog Application Key from GitHub Actions Secrets'
    required: true
  repo_path:
    description: 'Repository path'
    required: true
  wf:
    description: 'List of the desired workflows to be monitored (comma seperated)'
    required: true
  tag_workflow_id:
    description: 'One tag per WF from strategy matrix'
    required: true
  github_tk:
    description: 'Github Token'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Get latest timing trough GitHub API request
      uses: octokit/request-action@v2.1.0 # using official request action from octokit
      id: get_latest_timing
      with:
        route: GET /repos/${{ inputs.repo_path }}/actions/workflows/${{ inputs.wf }}/timing
      env:
        GITHUB_TOKEN: ${{ inputs.github_tk }}

    - name: API Output response check
      shell: bash
      run: echo ${{ toJSON(fromJSON(steps.get_latest_timing.outputs.data).billable.UBUNTU.total_ms) }}

    - name: Calculate and post latest timing to Datatdog as Custom Metric
      shell: bash
      id: post_latest_timing
      run: |
          min=$(($latest_total_ms_ubuntu / 60000))
          echo $min
          export NOW="$(date +%s)"
          curl -X POST "https://api.datadoghq.eu/api/v1/series" \
          -H "Content-Type: text/json" \
          -H "DD-API-KEY: $DD_API_KEY" \
          -d @- << EOF
          {
            "series": [
              {
                "metric": "github.actions.minutes",
                "points": [[${NOW}, $min]],
                "tags": "workflow:$tag_workflow_id",
                "type": "gauge"
              }
            ]
          }
          EOF
      env:
        # Datadog API and Application Keys (stored in GitHub Actions Secrets)
        DD_API_KEY: ${{ inputs.api_key }}
        DD_APP_KEY: ${{ inputs.app_key }}
        latest_total_ms_ubuntu: ${{ toJSON(fromJSON(steps.get_latest_timing.outputs.data).billable.UBUNTU.total_ms) }}
        tag_workflow_id: ${{ inputs.wf }} # Creates a tag on datadog for each workflow