name: Workflow Usage Datadog Custom Metric

author: Domenic Gosein

description: GitHub Action to send minutes usage per workflow to a custom metric in Datadog.

branding:
  icon: 'clock'  
  color: 'orange'

inputs:
  api_key:
    description: 'Datadog API key e.g. from GitHub Actions Secrets'
    required: true
  app_key:
    description: 'Datadog Application Key e.g. from GitHub Actions Secrets.'
    required: true
  repo_path:
    description: 'Repository path e.g. from standard variable.'
    required: true
  wf:
    description: 'Workflow name from strategy matrix.'
    required: true
  tag_workflow_id:
    description: 'Workflow name from strategy matrix.'
    required: true
  github_tk:
    description: 'Github Actions Token from GitHub Actions Secrets.'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Get latest timing trough GitHub API request
      uses: octokit/request-action@v2.1.0
      id: get_latest_timing
      with:
        route: GET /repos/${{ inputs.repo_path }}/actions/workflows/${{ inputs.wf }}/timing
      env:
        GITHUB_TOKEN: ${{ inputs.github_tk }}

    - name: Value check received from API request
      shell: bash
      run: echo ${{ toJSON(fromJSON(steps.get_latest_timing.outputs.data).billable.UBUNTU.total_ms) }}

    - name: Calculate and post latest timing in minutes to Datatdog as a Custom Metric
      shell: bash
      id: post_latest_timing
      run: |
          min=$(($latest_total_ms_ubuntu / 60000))
          echo $min
          export NOW="$(date +%s)"
          curl -X POST "https://api.datadoghq.eu/api/v1/series" \
          -H "Content-Type: text/json" \
          -H "DD-API-KEY: $DD_API_KEY" \
          -d @- << EOF
          {
            "series": [
              {
                "metric": "github.actions.minutes",
                "points": [[${NOW}, $min]],
                "tags": "workflow:$tag_workflow_id",
                "type": "gauge"
              }
            ]
          }
          EOF
      env:
        DD_API_KEY: ${{ inputs.api_key }}
        DD_APP_KEY: ${{ inputs.app_key }}
        latest_total_ms_ubuntu: ${{ toJSON(fromJSON(steps.get_latest_timing.outputs.data).billable.UBUNTU.total_ms) }}
        tag_workflow_id: ${{ inputs.wf }}