name: Another Test WF

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test-print:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Question
        run: |
          echo "Does it work now !??"
