name: GitHub Minutes Report

on:
  workflow_run:
    workflows: [Datadog, Test WF] # To do: Get all workflows from Repo and include them here
    types:
      - completed

jobs:
  updateWorkflowTimings:
    runs-on: ubuntu-latest
    env:
      WF: datadog.yml # To do: Get all workflows from Repo and execute API request for all of them
    steps:
      - uses: octokit/request-action@v2.1.0
        id: get_latest_timing
        with:
          route: GET /repos/${{ github.repository }}/actions/workflows/${{ env.WF }}/timing
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: "echo latest timing for ${{ env.WF }}: ${{ steps.get_latest_timing.outputs.billable.UBUNTU }}"